// Builds supabase/seed/02_areas.sql and 03_buildings.sql from the OSM snapshots
// in supabase/seed/osm (fetched once from Overpass; © OpenStreetMap, ODbL).
// Re-run after refreshing snapshots:  npm run seed:build
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  designatorSlug, districtNames, districtSearchText, normalizeHouseNumber, parseDistrictDesignator,
} from '../packages/normalization/src/text.ts'

const root = new URL('..', import.meta.url).pathname
const seedDir = join(root, 'supabase/seed')

type OsmWay = { type: 'way'; id: number; tags: Record<string, string>; geometry?: Array<{ lat: number; lon: number }> }
type Addr = { id: string; street: string | null; house: string | null; lat: number; lon: number; building?: string }

const ways = (JSON.parse(readFileSync(join(seedDir, 'osm/aktau-microdistricts.json'), 'utf8')).elements as OsmWay[])
const addrFile = JSON.parse(readFileSync(join(seedDir, 'osm/aktau-addresses.json'), 'utf8'))
const addrs = addrFile.elements as Addr[]

const q = (s: string | null | undefined) => (s == null ? 'null' : `'${s.replace(/'/g, "''")}'`)

// ── Areas ────────────────────────────────────────────────────────────────────
const polygonsByDesignator = new Map<string, Array<{ osmId: number; ring: number[][]; place?: string }>>()
for (const w of ways) {
  const name = w.tags.name ?? ''
  const d = parseDistrictDesignator(name)
  const g = w.geometry ?? []
  const closed = g.length >= 4 && g[0]!.lat === g.at(-1)!.lat && g[0]!.lon === g.at(-1)!.lon
  if (!d || !closed) continue
  const list = polygonsByDesignator.get(d) ?? []
  list.push({ osmId: w.id, ring: g.map((p) => [p.lon, p.lat]), place: w.tags.place })
  polygonsByDesignator.set(d, list)
}

const buildingDesignators = new Set<string>()
for (const a of addrs) {
  const d = a.street ? parseDistrictDesignator(a.street) : null
  if (d && a.house) buildingDesignators.add(d)
}

const designators = [...new Set([...polygonsByDesignator.keys(), ...buildingDesignators])].sort((a, b) => {
  const na = parseInt(a, 10), nb = parseInt(b, 10)
  if (Number.isNaN(na) && Number.isNaN(nb)) return a.localeCompare(b)
  if (Number.isNaN(na)) return 1
  if (Number.isNaN(nb)) return -1
  return na - nb || a.localeCompare(b)
})

const areaSql: string[] = [
  '-- GENERATED by scripts/build-seed.ts from OpenStreetMap (© OpenStreetMap contributors, ODbL 1.0).',
  '-- Microdistrict polygons are the union of all closed OSM ways naming the district.',
  '-- Districts without a mapped polygon get a hull of their addressed buildings (04_derived_geometry.sql).',
  '',
]
for (const d of designators) {
  const names = districtNames(d)
  const polys = polygonsByDesignator.get(d) ?? []
  const geom = polys.length
    ? `(select ST_Multi(ST_Union(ST_MakeValid(ST_GeomFromGeoJSON(g))))::geography from (values ${polys
        .map((p) => `(${q(JSON.stringify({ type: 'Polygon', coordinates: [p.ring.map(([x, y]) => [+x!.toFixed(6), +y!.toFixed(6)])] }))})`)
        .join(', ')}) v(g))`
    : 'null'
  const meta = { geometry_source: polys.length ? 'osm_polygons' : 'pending_buildings_hull', osm_way_ids: polys.map((p) => p.osmId) }
  areaSql.push(
    `insert into areas (slug, name, name_en, name_ru, name_kk, area_type, designator, geometry, search_text, metadata) values (` +
      `${q(designatorSlug(d))}, ${q(names.en)}, ${q(names.en)}, ${q(names.ru)}, ${q(names.kk)}, 'MICRODISTRICT', ${q(d)}, ${geom}, ` +
      `${q(districtSearchText(d))}, ${q(JSON.stringify(meta))}::jsonb) on conflict (slug) do nothing;`,
  )
}
areaSql.push('', 'update areas set centroid = ST_PointOnSurface(geometry::geometry)::geography where geometry is not null and centroid is null;')
writeFileSync(join(seedDir, '02_areas.sql'), areaSql.join('\n') + '\n')

// ── Buildings ───────────────────────────────────────────────────────────────
const seen = new Set<string>()
const rows: string[] = []
for (const a of addrs) {
  const d = a.street ? parseDistrictDesignator(a.street) : null
  if (!d || !a.house) continue
  const house = a.house.trim()
  if (!/^\d/.test(house) || house.length > 12) continue // skip 'мкр дом 2'-style noise
  const norm = normalizeHouseNumber(house)
  const key = `${d}|${norm}`
  if (seen.has(key)) continue
  seen.add(key)
  const names = districtNames(d)
  rows.push(
    `(${q(designatorSlug(d))}, ${q(house)}, ${q(norm)}, ${q(`${names.ru}, ${house}`)}, ` +
      `ST_SetSRID(ST_MakePoint(${a.lon}, ${a.lat}), 4326)::geography, ${q(a.id)}, ${q(JSON.stringify({ osm: a.id }))}::jsonb)`,
  )
}
const bSql = [
  '-- GENERATED by scripts/build-seed.ts from OpenStreetMap addresses (© OpenStreetMap contributors, ODbL 1.0).',
  `-- ${rows.length} buildings addressed "<N> микрорайон, <house>".`,
  '',
]
for (let i = 0; i < rows.length; i += 400) {
  bSql.push(
    'insert into buildings (area_id, house_number, house_number_norm, display_address, point, osm_id, external_ids)',
    `select a.id, v.house, v.norm, v.addr, v.pt, v.osm, v.ext from (values\n  ${rows.slice(i, i + 400).join(',\n  ')}\n) v(slug, house, norm, addr, pt, osm, ext)`,
    'join areas a on a.slug = v.slug on conflict (area_id, house_number_norm) do nothing;',
    '',
  )
}
writeFileSync(join(seedDir, '03_buildings.sql'), bSql.join('\n'))

// Trim the address snapshot to what the seed actually uses (keeps the repo lean).
const used = addrs.filter((a) => a.street && parseDistrictDesignator(a.street) && a.house)
writeFileSync(join(seedDir, 'osm/aktau-addresses.json'), JSON.stringify({ ...addrFile, elements: used }))

// ── Coastline (Caspian Safety) ──────────────────────────────────────────────
const coast = (JSON.parse(readFileSync(join(seedDir, 'osm/aktau-coastline.json'), 'utf8')).elements as OsmWay[])
  .filter((w) => (w.geometry?.length ?? 0) >= 2)
const cSql = [
  '-- GENERATED by scripts/build-seed.ts from OpenStreetMap natural=coastline (© OpenStreetMap contributors, ODbL 1.0).',
  '-- Used to draw official / prohibited stretches of shore and to tell whether a point is on the coast.',
  '',
  ...coast.map((w) => `insert into coastline (osm_id, geometry) values (${w.id}, ST_GeomFromGeoJSON(${q(JSON.stringify({
    type: 'LineString', coordinates: w.geometry!.map((p) => [p.lon, p.lat]),
  }))})::geography) on conflict (osm_id) do nothing;`),
]
writeFileSync(join(seedDir, '05_coastline.sql'), cSql.join('\n') + '\n')

console.log(`areas: ${designators.length} (${polygonsByDesignator.size} with OSM polygons) · buildings: ${rows.length} · coastline ways: ${coast.length}`)
